
package proyecto;

unit TestGeneral;

rule "Perdida de puntos"
when
	$d: /drivers[$points : points];
	/violations[type.equals("speed"), actualspeed-speedlimit>=30];
then
    $d.setPoints($points+7);
end
rule"velocidad2"
when
	$d: /drivers[$points : points];
	/violations[type.equals("speed"), actualspeed-speedlimit<30];
then
    $d.setPoints($points+3);
end
rule"parking"
when
	$d: /drivers[$points : points];
	/violations[type.equals("parking")];
then
    $d.setPoints($points+1);
end
rule"sustancias"
when
	$d: /drivers[$points : points];
	/violations[type.equals("driving under the influence")];
then
    $d.setPoints($points+5);
end


